### ISSUE TITLE
Not compatible with Ubuntu 18.10 now

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [coturn/coturn#320]
Ubuntu is now using OpenSSL 1.1.0g but it semms that coturn is still requiring OpenSSL 1.0.x

```
/usr/bin/ld: warning: libssl.so.1.1, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libevent_openssl.so, may conflict with libssl.so.1.0.0
/usr/bin/ld: /tmp/ccrkM3nF.o: undefined reference to symbol 'TLS_server_method@@OPENSSL_1_1_0'
//usr/lib/x86_64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line
```

**Comment by misi** [comment]
Have you tried to build with openssl 1.1.0g?

**Comment by Aster-the-Med-Stu** [comment]
@misi I can confirm it, as removing libssl-dev for libssl1.0-dev could successfully build this.

**Comment by alexisprevot** [comment]
In Ubuntu 18.04 you can just fire as root

```
sudo apt-get install coturn
```

Once it's done, you can forget `./configure`, `make` and `make install` and continue the installation following the INSTALL document.

**Comment by eakraly** [comment]
This issue is 2 years old and is very specific to that year - talking about ubuntu 18.10
Closing the issue
Please open a new one if you still have an issue
