### ISSUE TITLE
Coturn failes to build on Ubuntu 22.04: undefined reference to `FIPS_mode'

### ISSUE THREAD

**Issue by mesonium** [coturn/coturn#1050]
I try to install coturn by source:
```
git clone https://github.com/coturn/coturn
cd coturn && ./configure --prefix=/opt --openssl=../openssl-3.0.5
```
Output:
```
ginstall: not found
install is /usr/bin/install
pkill is /usr/bin/pkill
sqlite3 is /usr/bin/sqlite3
Use TMP dir /var/tmp
Compiler: cc
pkgconf is /usr/bin/pkgconf
pkg-config: pkgconf
Library option -lsocket cannot be used
Library option -lwldap32 cannot be used
Library option -lwldap64 cannot be used
Sockets code is fine: no sin_len field present
Ignore IP_RECVERR
OpenSSL Crypto lib found.
OpenSSL lib found.
Libevent2 runtime found.
Library option -lprom cannot be used

Warning: Libprom development libraries are not installed properly in required location.
Prometheus support will be disabled.
See the INSTALL file.

Systemd library found.
SQLite3 library found.
PostgreSQL not found. Building without PostgreSQL support.
./configure: 54: mysql_config: not found
./configure: 55: mysql_config: not found
MySQL not found. Building without MySQL support.
MongoDB not found. Building without MongoDB support.
Hiredis not found. Building without hiredis support.
PREFIX=/opt LOCALSTATEDIR=/opt/var OSLIBS= -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib DBLIBS= -lsqlite3   OSCFLAGS=-g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb DBCFLAGS=   --prefix=/opt --openssl=../openssl-3.0.5
Makefile created: success.
```

However, it fails when compiling it with `make`:
```
mkdir -p build/obj
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  -c src/client/ns_turn_ioaddr.c -o build/obj/ns_turn_ioaddr.o
mkdir -p build/obj
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  -c src/client/ns_turn_msg_addr.c -o build/obj/ns_turn_msg_addr.o
mkdir -p build/obj
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  -c src/client/ns_turn_msg.c -o build/obj/ns_turn_msg.o
src/client/ns_turn_msg.c: In function ‘stun_attr_add_integrity_str’:
src/client/ns_turn_msg.c:1855:12: warning: ‘hmac’ may be used uninitialized [-Wmaybe-uninitialized]
 1855 |         if(stun_attr_add_str(buf, len, STUN_ATTRIBUTE_MESSAGE_INTEGRITY, hmac, shasize)<0)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/client/ns_turn_msg.c:1441:5: note: by argument 4 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} to ‘stun_attr_add_str’ declared here
 1441 | int stun_attr_add_str(uint8_t* buf, size_t *len, uint16_t attr, const uint8_t* avalue, int alen) {
      |     ^~~~~~~~~~~~~~~~~
src/client/ns_turn_msg.c:1837:17: note: ‘hmac’ declared here
 1837 |         uint8_t hmac[MAXSHASIZE];
      |                 ^~~~
mkdir -p lib
ar -r lib/libturnclient.a build/obj/ns_turn_ioaddr.o build/obj/ns_turn_msg_addr.o build/obj/ns_turn_msg.o 
ar: creating lib/libturnclient.a
pwd
/home/user/sources/coturn
mkdir -p bin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  src/apps/oauth/oauth.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c -o bin/turnutils_oauth -Llib -lturnclient -Llib -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib
/usr/bin/ld: lib/libturnclient.a(ns_turn_msg.o): in function `stun_produce_integrity_key_str':
/home/user/sources/coturn/src/client/ns_turn_msg.c:260: undefined reference to `FIPS_mode'
collect2: error: ld returned 1 exit status
make: *** [Makefile:121: bin/turnutils_oauth] Error 1
```

If I comment out the appropiate line in `/home/user/sources/coturn/src/client/ns_turn_msg.c`
```
-#if defined EVP_MD_CTX_FLAG_NON_FIPS_ALLOW && ! defined(LIBRESSL_VERSION_NUMBER)
-               if (FIPS_mode()) {
-                       EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
-               }
-#endif
+//#if defined EVP_MD_CTX_FLAG_NON_FIPS_ALLOW && ! defined(LIBRESSL_VERSION_NUMBER)
+//             if (FIPS_mode()) {
+//                     EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
+//             }
+//#endif
```

it still doesn't build:

```
mkdir -p build/obj
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  -c src/client/ns_turn_msg.c -o build/obj/ns_turn_msg.o
src/client/ns_turn_msg.c: In function ‘stun_attr_add_integrity_str’:
src/client/ns_turn_msg.c:1855:12: warning: ‘hmac’ may be used uninitialized [-Wmaybe-uninitialized]
 1855 |         if(stun_attr_add_str(buf, len, STUN_ATTRIBUTE_MESSAGE_INTEGRITY, hmac, shasize)<0)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/client/ns_turn_msg.c:1441:5: note: by argument 4 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} to ‘stun_attr_add_str’ declared here
 1441 | int stun_attr_add_str(uint8_t* buf, size_t *len, uint16_t attr, const uint8_t* avalue, int alen) {
      |     ^~~~~~~~~~~~~~~~~
src/client/ns_turn_msg.c:1837:17: note: ‘hmac’ declared here
 1837 |         uint8_t hmac[MAXSHASIZE];
      |                 ^~~~
mkdir -p lib
ar -r lib/libturnclient.a build/obj/ns_turn_ioaddr.o build/obj/ns_turn_msg_addr.o build/obj/ns_turn_msg.o 
pwd
/home/user/sources/coturn
mkdir -p bin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  src/apps/oauth/oauth.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c -o bin/turnutils_oauth -Llib -lturnclient -Llib -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib
pwd
/home/user/sources/coturn
mkdir -p bin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  src/apps/natdiscovery/natdiscovery.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c -o bin/turnutils_natdiscovery -Llib -lturnclient -Llib -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib
pwd
/home/user/sources/coturn
mkdir -p bin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  src/apps/stunclient/stunclient.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c -o bin/turnutils_stunclient -Llib -lturnclient -Llib -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib   
pwd
/home/user/sources/coturn
mkdir -p bin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  src/apps/rfc5769/rfc5769check.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c -o bin/turnutils_rfc5769check -Llib -lturnclient -Llib -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib 
mkdir -p bin
cc  -g  -Wall -Wno-deprecated-declarations -Wextra -Wformat-security -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Wcast-qual  -DTURN_HAS_DAEMON    -DTURN_NO_PROMETHEUS        -DINSTALL_PREFIX=/opt -DTURNDB=/opt/var/db/turndb -Isrc -Isrc/apps/common -Isrc/server -Isrc/client -Isrc/client++ -I/opt/include/ -I/usr/local/include/  src/apps/uclient/uclient.c src/apps/uclient/startuclient.c src/apps/uclient/mainuclient.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c -o bin/turnutils_uclient -Llib -lturnclient -Llib -lrt -lnsl -lresolv -lcrypto  -lssl  -levent_core -levent_extra -levent_openssl -levent_pthreads -levent  -lsystemd   -Wl,-rpath,/usr/local/lib  
/usr/bin/ld: /tmp/ccs7mugw.o: in function `tls_connect':
/home/user/sources/coturn/src/apps/uclient/startuclient.c:141: undefined reference to `SSL_get_peer_certificate'
/usr/bin/ld: /home/user/sources/coturn/src/apps/uclient/startuclient.c:143: undefined reference to `SSL_get_peer_certificate'
/usr/bin/ld: /home/user/sources/coturn/src/apps/uclient/startuclient.c:175: undefined reference to `SSL_get_peer_certificate'
/usr/bin/ld: /home/user/sources/coturn/src/apps/uclient/startuclient.c:184: undefined reference to `SSL_get_peer_certificate'
collect2: error: ld returned 1 exit status
make: *** [Makefile:111: bin/turnutils_uclient] Error 1
```

### System
coturn git master + 4.6.0
OpenSSL 3.0.5
Ubuntu 22.04

**Comment by mesonium** [comment]
I have also seen https://github.com/coturn/coturn/commit/4ce784a8781ab086c150e2b9f5641b1a37fd9b31 which is part of the git history of the build above, but it doesn't seem to fix the issue for me.

**Comment by eakraly** [comment]
Hi @mesonium !
I just tested myself in a docker container and could build with openssl-3.0.5
I have a strong feeling that your build picks up older (pre-3.0) openssl header files in the path and uses them

The only way compiler would get to `FIPS_mode()` is if OPENSSL_VERSION_NUMBER < 0x30000000L - which means it is defined but not as `0x30NN0000L`

**Comment by mesonium** [comment]
You were right, it somehow picked up the wrong header files of a older version I had installed. My bad! :)
