### ISSUE TITLE
coturn-4.10.0 build failure

### ISSUE THREAD

**Issue by kennethanderson** [coturn/coturn#1867]
Release 4.10 contains commit 3294c71, which introduced a reference to 'struct mmsghdr' in src/apps/relay/dtls_listener.c : line 129.

<img width="903" height="255" alt="Image" src="https://github.com/user-attachments/assets/1beb5a3f-a111-4d84-b00f-435600aae57f" />

Accdording to the recvmmsg man page, this structure is available if _GNU_SOURCE is defined:

<img width="997" height="528" alt="Image" src="https://github.com/user-attachments/assets/322fb473-eaf7-46b7-b8d4-211f1cb98f4a" />

For Linux build environments that do not define _GNU_SOURCE by default, the build will fail:

```
cd coturn
./configure
make

...

src/apps/relay/dtls_listener.c:129:18: error: array type has incomplete element type 'struct mmsghdr'
  129 |   struct mmsghdr msgs[MAX_RECVMMSG_BATCH];
      |                  ^~~~
src/apps/relay/dtls_listener.c: In function 'receive_udp_batch_recvmmsg':
src/apps/relay/dtls_listener.c:748:18: warning: implicit declaration of function 'recvmmsg'; did you mean 'recvmsg'? [-Wimplicit-function-declaration]
  748 |   const int rc = recvmmsg(fd, state->msgs, i, MSG_DONTWAIT, NULL);
      |                  ^~~~~~~~
      |                  recvmsg
src/apps/relay/dtls_listener.c:748:18: warning: nested extern declaration of 'recvmmsg' [-Wnested-externs]
make: *** [Makefile:142: bin/turnserver] Error 1
```

# Workaround

The configure script probably needs to be updated.  But in the meantime, for others who experience this, a workaround is to pass in the definition during configuration:

```
export LDFLAGS="-D_GNU_SOURCE"
cd coturn
./configure
make
```

**Comment by kennethanderson** [comment]
The problem does not occur for coturn-4.9.0.  It builds fine without "-D_GNU_SOURCE".

**Comment by eakraly** [comment]
Thanks @kennethanderson . What distro are you building with so that you found this out?

**Comment by kennethanderson** [comment]
It is a custom linux build using libevent version 2.1.7.  That version of libevent does not define _GNU_SOURCE in it's header files (event2/event-config.h).  If you are able to downgrade libevent-dev, you'll probably see the error.

libevent version 2.1.12 does define _GNU_SOURCE.  So this error can also be fixed by upgrading libevent.  But in that case, CMake should probably do a version check on the library.
