### ISSUE TITLE
Can CoTurn be installed on macOS？

### ISSUE THREAD

**Issue by phpisfuture** [coturn/coturn#597]
Can CoTurn be installed on macOS？

./configure is success,but make reports an error,So how do we solve this？

1 warning generated.
Undefined symbols for architecture x86_64:
  "_FIPS_mode", referenced from:
      _stun_produce_integrity_key_str in libturnclient.a(ns_turn_msg.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/turnutils_oauth] Error 1

**Comment by misi** [comment]
According travis it works with xcode 10.3 and xcode 9.4

**Comment by phpisfuture** [comment]
Can't other versions?

**Comment by Nais0ne** [comment]
Just use the docker version of coturn

**Comment by xuandu** [comment]
hello ,have you install successfully at macOS? I have the same problem with you .

**Comment by phpisfuture** [comment]
> hello ,have you install successfully at macOS? I have the same problem with you .

not，I installed it with Docker。
